services:
  edrys_arm_development:
    build: .
    image: edrys_arm_development
    privileged: true
    container_name: edrys_arm_development
    ports:
      - "5000:5000"
    environment:
      - PYXTERM_CMD=zsh
    devices:
      - /dev/ttyACM0
    volumes:
      #            +- user path
      #            v
      - /media/sebastian/DIS_L4IOT:/media/appuser/DIS_L4IOT
      - /dev/disk/by-id:/dev/disk/by-id
      - /dev/serial/by-id:/dev/serial/by-id
      - /run/udev:/run/udev:ro